apiVersion: v1
kind: Secret
metadata:
  name: govbi-ia-secrets
type: Opaque
stringData:
  GOVBI_SQLSERVER_PASSWORD: "trocar-em-producao"
  GOVBI_DATABRICKS_TOKEN: "trocar-em-producao"
  GOVBI_OPENAI_API_KEY: "trocar-em-producao"
